spring:
  application:
    name: emploject
  datasource:
    url: jdbc:h2:mem:emploject_db
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop